package com.ks.zkclient;

import com.ks.rmizkinterface.ZKManager;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.rmi.NotBoundException;
import java.rmi.RMISecurityManager;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin Sapper (2012)
 */
public class ZKFrame extends javax.swing.JFrame {

    private ZKManager zKManager;
    
    private ZkManagementPanel zkManagementPanel;
    
    private ZkPanel zkPanel;

    private static int port;

    /**
     * Creates new form ZKFrame
     */
    public ZKFrame() {
        initComponents();
        
        // Create and install a security manager
        if (System.getSecurityManager() == null) {
            System.setSecurityManager(new RMISecurityManager());
        }

        try {
            String name = "zkManager";
            Registry registry = LocateRegistry.getRegistry(port);
            zKManager = (ZKManager) registry.lookup(name);
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(ZKFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        zkPanel = new ZkPanel(zKManager, this);
        this.add(zkPanel, BorderLayout.WEST);
        zkPanel.setVisible(false);
        
        zkManagementPanel = new ZkManagementPanel(zKManager, this);
        this.add(zkManagementPanel, BorderLayout.CENTER);
        zkManagementPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Zeichenkettenclient"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZKFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZKFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZKFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZKFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        port = 6000;
        if (args.length > 0) {
            try {
                port = Integer.valueOf(args[0]);
            } catch (NumberFormatException ex) {
            }
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZKFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void actionZkPanel(String id) {
        zkPanel.actionShow(id);
    }
    
    public void switchPanels() {
        this.zkPanel.setVisible(!zkPanel.isVisible());
        this.zkManagementPanel.setVisible(!zkManagementPanel.isVisible());
        pack();
    }
}
