/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HighscoreCard.java
 *
 * Created on 09.01.2012, 17:27:35
 */
package org.ks.frogger.cards;

import java.awt.Color;
import java.awt.event.ActionListener;
import org.ks.frogger.ActionCommand;

/**
 *
 * @author Sappo
 */
public class HighscoreCard extends javax.swing.JPanel {

  /** Creates new form HighscoreCard */
  public HighscoreCard(ActionListener listener) {
    initComponents();
    backButton.setActionCommand(ActionCommand.SHOWOPENING);
    backButton.addActionListener(listener);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        topTenLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setFocusable(false);
        setFont(new java.awt.Font("Kristen ITC", 0, 24));
        setMaximumSize(new java.awt.Dimension(500, 600));
        setName("highscore"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Kristen ITC", 1, 60)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Highscore");
        headerLabel.setFocusable(false);
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerLabel.setMaximumSize(new java.awt.Dimension(330, 80));
        headerLabel.setMinimumSize(new java.awt.Dimension(330, 80));
        headerLabel.setOpaque(true);
        headerLabel.setPreferredSize(new java.awt.Dimension(330, 80));

        topTenLabel.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        topTenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topTenLabel.setText("TOP TEN");

        backButton.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        backButton.setText("Main-Menu");
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(topTenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(191, 191, 191))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topTenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    
  }//GEN-LAST:event_formMouseEntered

  private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    
  }//GEN-LAST:event_formMouseExited

  private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
    backButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_backButtonMouseEntered

  private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
    backButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_backButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel topTenLabel;
    // End of variables declaration//GEN-END:variables
}
