/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartCard.java
 *
 * Created on 09.01.2012, 19:10:47
 */
package org.ks.frogger.cards;

import java.awt.Color;
import java.awt.event.ActionListener;
import org.ks.frogger.ActionCommand;

/**
 *
 * @author Sappo
 */
public class OpeningCard extends javax.swing.JPanel {

  /** Creates new form StartCard */
  public OpeningCard(ActionListener actionListener) {
    initComponents();
    
    stagesButton.setActionCommand(ActionCommand.SHOWSTAGES);
    stagesButton.addActionListener(actionListener);
    
    highscoreButton.setActionCommand(ActionCommand.SHOWHIGHSCORE);
    highscoreButton.addActionListener(actionListener);
    
    exitButton.setActionCommand(ActionCommand.EXIT);
    exitButton.addActionListener(actionListener);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        stagesButton = new javax.swing.JButton();
        highscoreButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setMaximumSize(new java.awt.Dimension(500, 600));
        setName("openingPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 600));

        exitButton.setFont(new java.awt.Font("Kristen ITC", 1, 60)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });

        stagesButton.setFont(new java.awt.Font("Kristen ITC", 1, 60)); // NOI18N
        stagesButton.setText("Stages");
        stagesButton.setBorder(null);
        stagesButton.setBorderPainted(false);
        stagesButton.setContentAreaFilled(false);
        stagesButton.setFocusPainted(false);
        stagesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stagesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stagesButtonMouseExited(evt);
            }
        });

        highscoreButton.setFont(new java.awt.Font("Kristen ITC", 1, 60)); // NOI18N
        highscoreButton.setText("Highscore");
        highscoreButton.setBorder(null);
        highscoreButton.setBorderPainted(false);
        highscoreButton.setContentAreaFilled(false);
        highscoreButton.setFocusPainted(false);
        highscoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                highscoreButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                highscoreButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(stagesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(highscoreButton)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(stagesButton)
                .addGap(26, 26, 26)
                .addComponent(highscoreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
    exitButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_exitButtonMouseEntered

  private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
    exitButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_exitButtonMouseExited

  private void highscoreButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highscoreButtonMouseEntered
    highscoreButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_highscoreButtonMouseEntered

  private void highscoreButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highscoreButtonMouseExited
    highscoreButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_highscoreButtonMouseExited

  private void stagesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stagesButtonMouseEntered
    stagesButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_stagesButtonMouseEntered

  private void stagesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stagesButtonMouseExited
    stagesButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_stagesButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton highscoreButton;
    private javax.swing.JButton stagesButton;
    // End of variables declaration//GEN-END:variables
}
