/*
 * GameOverCard.java
 *
 * Created on 10.01.2012, 21:39:40
 */
package org.ks.frogger.cards;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import javax.annotation.PostConstruct;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Singleton;
import org.ks.frogger.ActionCommand;
import org.ks.frogger.events.GameOver;
import org.ks.frogger.stages.StageManager;

/**
 *
 * @author Sappo
 */
@Singleton
public class StagesCard extends javax.swing.JPanel {

  @Inject
  private StageManager stageManager;

  @PostConstruct
  public void initialize() {
    initComponents();
    mainButton.setActionCommand(ActionCommand.SHOWOPENING);

    playButton.setActionCommand(ActionCommand.NEWGAME);

    stageManager.setupStages(this);

    updateStageValues();
  }
  
  public void addActionListener(ActionListener listener){
    mainButton.addActionListener(listener);
    playButton.addActionListener(listener);
  }

  private void updateStageValues() {
    previousButton.setVisible(!stageManager.getCurrentStage().isFirstStage());
    nextButton.setVisible(stageManager.getCurrentStage().isNextStageUnlocked());
  }
  
  public void listenToGameOver(@Observes @GameOver long highscore) {
    //@TODO show game score on game over 
  }

  @Override
  protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    g.drawImage(stageManager.getCurrentStage().getStageImage(), 12, 146, null);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setMaximumSize(new java.awt.Dimension(500, 600));

        headerLabel.setFont(new java.awt.Font("Kristen ITC", 0, 48));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Stage");

        nextButton.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        nextButton.setText("Next Stage");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setFocusPainted(false);
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });

        previousButton.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        previousButton.setText("Previous Stage");
        previousButton.setBorder(null);
        previousButton.setBorderPainted(false);
        previousButton.setContentAreaFilled(false);
        previousButton.setFocusPainted(false);
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previousButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previousButtonMouseExited(evt);
            }
        });

        mainButton.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        mainButton.setText("Main-Menu");
        mainButton.setActionCommand("SHOWOPENING");
        mainButton.setBorder(null);
        mainButton.setBorderPainted(false);
        mainButton.setContentAreaFilled(false);
        mainButton.setFocusPainted(false);
        mainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainButtonMouseExited(evt);
            }
        });

        playButton.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        playButton.setText("Play Stage");
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButtonMouseExited(evt);
            }
        });

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(previousButton)
                                .addGap(69, 69, 69)
                                .addComponent(mainButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(nextButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addGap(64, 64, 64)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(previousButton)
                    .addComponent(mainButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void mainButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainButtonMouseEntered
    mainButton.setForeground(Color.WHITE);

  }//GEN-LAST:event_mainButtonMouseEntered

  private void mainButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainButtonMouseExited
    mainButton.setForeground(Color.BLACK);

  }//GEN-LAST:event_mainButtonMouseExited

  private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
    nextButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_nextButtonMouseEntered

  private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
    nextButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_nextButtonMouseExited

  private void previousButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseEntered
    previousButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_previousButtonMouseEntered

  private void previousButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseExited
    previousButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_previousButtonMouseExited

  private void playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseEntered
    playButton.setForeground(Color.WHITE);
  }//GEN-LAST:event_playButtonMouseEntered

  private void playButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseExited
    playButton.setForeground(Color.BLACK);
  }//GEN-LAST:event_playButtonMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton mainButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
